### PR TITLE
Fix re-computation problem #44

### LINKED ISSUE #44: V1.2.3 crash
Crash when opening the button "use POST method"  Tried reinstalling but it didn't work

but V1.2.2 can be used as usual

### PR DESCRIPTION
**Pull request by HSwift**
Fixed #44 in my chrome after removing all postControlWrapped related code

### CODE REVIEW

**Comment by 0140454** [comment]
Thanks for contribution!

However, please change commit title to `Remove ...`.

Furthermore, do you want to add yourself into Contributor list in README?

**Comment by HSwift** [comment]
It looks like I'm failing to change the commit titile. You may need to **squash and merge** this PR to change the commit titile.

**Comment by 0140454** [comment]
CI is relevant

**Comment by 0140454** [comment]
By the way, if we change `selectCenter != switchCenter` to `Math.ceil(selectCenter) != Math.ceil(switchCenter)`, does it work as expected?

Could you help me test it?

File: src/components/RequestPanelBasic.vue [hunk 1]
```diff
@@ -197,7 +197,7 @@ export default defineComponent({
       const switchCenter =
         postEnabledSwitchTop.value + postEnabledSwitchHeight.value / 2
 
-      return selectCenter != switchCenter
+      return Math.abs(selectCenter - switchCenter) < 0.0001
```
Comment (0140454) [inline src/components/RequestPanelBasic.vue:200]: Since the original code is `selectCenter != switchCenter`, it should use `>` operator here.

```suggestion
      return Math.abs(selectCenter - switchCenter) > 0.0001
```

**Review by 0140454 — CHANGES_REQUESTED** [review]

**Comment by 0140454** [comment]
CI is relevant.

You can execute `yarn lint:fix` to resolve it, and then update this PR.
